language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*

before_install:
  - composer require "symfony/config:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/dependency-injection:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/http-foundation:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/http-kernel:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/yml:${SYMFONY_VERSION}" --no-update

install:
  - composer update --prefer-source

script:
  - phpunit --coverage-text
